CREATE DATABASE COLLAGE;
USE COLLAGE;
DROP DATABASE COLLAGE;
CREATE TABLE STUDENT 
(ROLLNO INTEGER , 
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
BLOODGROUP VARCHAR(3),
EMAIL VARCHAR(30),
GENDER CHAR(1)
);
INSERT INTO STUDENT VALUES(1 , 'NILESH' , 'ROY CHOWDHURY' , 'A+' , 'NIL@GMAIL.COM' , 'M');-- VARIENT 1
INSERT INTO STUDENT VALUES(1 , 'NILESH' , 'ROY CHOWDHURY' , 'M' , 'NIL@GMAIL.COM'); -- ERROR
INSERT INTO STUDENT(FIRSTNAME , LASTNAME , ROLLNO , BLOODGROUP , EMAIL) VALUES('NILESH' , 'ROY CHOWDHURY' , 1 , 'A+' , 'NIL@GMAIL.COM');-- VARIENT 2


CREATE TABLE TEST
(A VARCHAR(30),
B VARCHAR(30)
);
INSERT INTO TEST VALUES('PRITAM' , 'SAHA');
INSERT INTO TEST VALUES('AGNIVA' , 'PAUL');
INSERT INTO STUDENT(FIRSTNAME , LASTNAME) SELECT * FROM TEST;

SELECT * FROM STUDENT;
SELECT  ROLLNO ,FIRSTNAME FROM STUDENT;

INSERT INTO STUDENT(FIRSTNAME,LASTNAME) SELECT B,A FROM TEST;


SELECT * FROM STUDENT where BLOODGROUP='A+';
SELECT * FROM STUDENT where ROLLNO=21;
SELECT * FROM STUDENT where BLOODGROUP='O' AND GENDER='F';
SELECT * FROM STUDENT where BLOODGROUP='O' OR GENDER='F';

SELECT * FROM STUDENT where ROLLNO>=5 AND ROLLNO<=10;
SELECT * FROM STUDENT where ROLLNO BETWEEN 5 AND 10;
SELECT * FROM STUDENT where GENDER<>'F';

SELECT * FROM STUDENT ORDER BY ROLLNO;


SELECT * FROM STUDENT ORDER BY ROLLNO DESC;


SELECT * FROM STUDENT ORDER BY BLOODGROUP ;

SELECT * FROM STUDENT ORDER BY FIRSTNAME , BLOODGROUP DESC;

insert into student values(25,'PRITAM','SAHA','A+','XYZgmail','M');
insert into student values(26,'PRITAM','SAHA','B+','ABC@gmail','M');

SELECT BLOODGROUP FROM STUDENT;
SELECT DISTINCT BLOODGROUP FROM STUDENT;

UPDATE STUDENT SET EMAIL='QWERTYyyyyy@GMAIL.COM' WHERE FIRSTNAME='emma';

UPDATE STUDENT SET EMAIL='QWERTYyyyyyZZZZZ@GMAIL.COM' , LASTNAME='WATSON' WHERE FIRSTNAME='EMMA';

DELETE FROM STUDENT WHERE BLOODGROUP='Z+';

TRUNCATE STUDENT;

UPDATE STUDENT SET EMAIL=NULL , LASTNAME='WATSON' WHERE FIRSTNAME='EMMA';

SELECT * FROM STUDENT ORDER BY FIRSTNAME;
SELECT * FROM STUDENT WHERE EMAIL IS NOT NULL;
SELECT * FROM STUDENT WHERE EMAIL IS NULL;

DESC STUDENT;

ALTER TABLE STUDENT MODIFY COLUMN EMAIL VARCHAR(50);

ALTER TABLE STUDENT MODIFY COLUMN EMAIL VARCHAR(5);
describe STUDENT;

ALTER TABLE STUDENT ADD COLUMN EMAIL VARCHAR(50);
ALTER TABLE STUDENT ADD COLUMN TEST VARCHAR(5);

ALTER TABLE STUDENT DROP COLUMN TEST;

CREATE TABLE STUDENT 
(ROLLNO INTEGER NOT NULL, 
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30),
BLOODGROUP VARCHAR(3),
EMAIL VARCHAR(30),
GENDER CHAR(1) NOT NULL
);

insert into student(FIRSTNAME) values ('BhadraAAAAAA');

ALTER TABLE STUDENT MODIFY COLUMN ROLLNO INTEGER NOT NULL;
describe STUDENT;
ALTER TABLE STUDENT MODIFY COLUMN ROLLNO INTEGER ;

CREATE TABLE STUDENT 
(ROLLNO INTEGER , 
FIRSTNAME VARCHAR(30),
LASTNAME VARCHAR(30),
BLOODGROUP VARCHAR(3),
EMAIL VARCHAR(30),
GENDER CHAR(1)
);

SELECT DISTINCT GENDER FROM STUDENT;
SELECT * FROM STUDENT;
ALTER TABLE STUDENT MODIFY COLUMN GENDER CHAR(1) DEFAULT '+';

ALTER TABLE STUDENT MODIFY COLUMN GENDER CHAR(1);

SELECT FIRSTNAME AS FIRST_NAME, LASTNAME AS LAST_NAME FROM STUDENT;